# Generated by Django 4.2.20 on 2025-04-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
            ],
        ),
    ]
